language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../Data_Structures
  - make -j
  - cd ./bin/
  - ./test_data_struct
notifications:
  email: false
